// Code generated by protoc-gen-go. DO NOT EDIT.
// source: docker-host.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DockerHost struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ColorCode            string   `protobuf:"bytes,3,opt,name=colorCode,proto3" json:"colorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerHost) Reset()         { *m = DockerHost{} }
func (m *DockerHost) String() string { return proto.CompactTextString(m) }
func (*DockerHost) ProtoMessage()    {}
func (*DockerHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_1358bea4b2532a29, []int{0}
}

func (m *DockerHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerHost.Unmarshal(m, b)
}
func (m *DockerHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerHost.Marshal(b, m, deterministic)
}
func (m *DockerHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerHost.Merge(m, src)
}
func (m *DockerHost) XXX_Size() int {
	return xxx_messageInfo_DockerHost.Size(m)
}
func (m *DockerHost) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerHost.DiscardUnknown(m)
}

var xxx_messageInfo_DockerHost proto.InternalMessageInfo

func (m *DockerHost) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DockerHost) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DockerHost) GetColorCode() string {
	if m != nil {
		return m.ColorCode
	}
	return ""
}

type HostContainerCount struct {
	Containers           map[string]int32 `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HostContainerCount) Reset()         { *m = HostContainerCount{} }
func (m *HostContainerCount) String() string { return proto.CompactTextString(m) }
func (*HostContainerCount) ProtoMessage()    {}
func (*HostContainerCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_1358bea4b2532a29, []int{1}
}

func (m *HostContainerCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostContainerCount.Unmarshal(m, b)
}
func (m *HostContainerCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostContainerCount.Marshal(b, m, deterministic)
}
func (m *HostContainerCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostContainerCount.Merge(m, src)
}
func (m *HostContainerCount) XXX_Size() int {
	return xxx_messageInfo_HostContainerCount.Size(m)
}
func (m *HostContainerCount) XXX_DiscardUnknown() {
	xxx_messageInfo_HostContainerCount.DiscardUnknown(m)
}

var xxx_messageInfo_HostContainerCount proto.InternalMessageInfo

func (m *HostContainerCount) GetContainers() map[string]int32 {
	if m != nil {
		return m.Containers
	}
	return nil
}

type GetContainersCountRequest struct {
	Hosts                []string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContainersCountRequest) Reset()         { *m = GetContainersCountRequest{} }
func (m *GetContainersCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetContainersCountRequest) ProtoMessage()    {}
func (*GetContainersCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1358bea4b2532a29, []int{2}
}

func (m *GetContainersCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainersCountRequest.Unmarshal(m, b)
}
func (m *GetContainersCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainersCountRequest.Marshal(b, m, deterministic)
}
func (m *GetContainersCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainersCountRequest.Merge(m, src)
}
func (m *GetContainersCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetContainersCountRequest.Size(m)
}
func (m *GetContainersCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainersCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainersCountRequest proto.InternalMessageInfo

func (m *GetContainersCountRequest) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type GetContainersCountResponse struct {
	HostContainers       []*HostContainerCount `protobuf:"bytes,1,rep,name=hostContainers,proto3" json:"hostContainers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetContainersCountResponse) Reset()         { *m = GetContainersCountResponse{} }
func (m *GetContainersCountResponse) String() string { return proto.CompactTextString(m) }
func (*GetContainersCountResponse) ProtoMessage()    {}
func (*GetContainersCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1358bea4b2532a29, []int{3}
}

func (m *GetContainersCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainersCountResponse.Unmarshal(m, b)
}
func (m *GetContainersCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainersCountResponse.Marshal(b, m, deterministic)
}
func (m *GetContainersCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainersCountResponse.Merge(m, src)
}
func (m *GetContainersCountResponse) XXX_Size() int {
	return xxx_messageInfo_GetContainersCountResponse.Size(m)
}
func (m *GetContainersCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainersCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainersCountResponse proto.InternalMessageInfo

func (m *GetContainersCountResponse) GetHostContainers() []*HostContainerCount {
	if m != nil {
		return m.HostContainers
	}
	return nil
}

func init() {
	proto.RegisterType((*DockerHost)(nil), "DockerHost")
	proto.RegisterType((*HostContainerCount)(nil), "HostContainerCount")
	proto.RegisterMapType((map[string]int32)(nil), "HostContainerCount.ContainersEntry")
	proto.RegisterType((*GetContainersCountRequest)(nil), "GetContainersCountRequest")
	proto.RegisterType((*GetContainersCountResponse)(nil), "GetContainersCountResponse")
}

func init() { proto.RegisterFile("docker-host.proto", fileDescriptor_1358bea4b2532a29) }

var fileDescriptor_1358bea4b2532a29 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x3d, 0x4f, 0xc3, 0x40,
	0x0c, 0x55, 0x92, 0x16, 0x29, 0x46, 0x2a, 0xd4, 0x30, 0x84, 0xc0, 0x50, 0x85, 0xa5, 0x0b, 0x91,
	0x28, 0x0b, 0x02, 0xb1, 0x10, 0x10, 0x2c, 0x30, 0x1c, 0x13, 0x6c, 0x49, 0x6a, 0xa9, 0x51, 0xcb,
	0x39, 0xdc, 0x5d, 0x2a, 0xf5, 0x9f, 0xf0, 0x73, 0x51, 0x2e, 0xb4, 0xa9, 0xfa, 0xb1, 0xd9, 0xcf,
	0x7e, 0xf7, 0xde, 0xf3, 0x41, 0x7f, 0xcc, 0xf9, 0x94, 0xd4, 0xd5, 0x84, 0xb5, 0x89, 0x4b, 0xc5,
	0x86, 0xa3, 0x77, 0x80, 0x27, 0x0b, 0xbe, 0xb2, 0x36, 0xd8, 0x03, 0xb7, 0x28, 0x03, 0x67, 0xe0,
	0x0c, 0x7d, 0xe1, 0x16, 0x25, 0x22, 0x74, 0x64, 0xfa, 0x4d, 0x81, 0x6b, 0x11, 0x5b, 0xe3, 0x05,
	0xf8, 0x39, 0xcf, 0x58, 0x25, 0x3c, 0xa6, 0xc0, 0xb3, 0x83, 0x16, 0x88, 0x7e, 0x1d, 0xc0, 0xfa,
	0xa9, 0x84, 0xa5, 0x49, 0x0b, 0x49, 0x2a, 0xe1, 0x4a, 0x1a, 0x4c, 0x00, 0xf2, 0x25, 0xa2, 0x03,
	0x67, 0xe0, 0x0d, 0x0f, 0x47, 0x97, 0xf1, 0xf6, 0x62, 0xbc, 0x6a, 0xf5, 0xb3, 0x34, 0x6a, 0x21,
	0xd6, 0x68, 0xe1, 0x03, 0x1c, 0x6d, 0x8c, 0xf1, 0x18, 0xbc, 0x29, 0x2d, 0xfe, 0x1d, 0xd7, 0x25,
	0x9e, 0x42, 0x77, 0x9e, 0xce, 0xaa, 0xc6, 0x73, 0x57, 0x34, 0xcd, 0x9d, 0x7b, 0xeb, 0x44, 0xd7,
	0x70, 0xf6, 0x42, 0xad, 0x9e, 0xb6, 0x82, 0x82, 0x7e, 0x2a, 0xd2, 0xa6, 0xa6, 0xd5, 0x57, 0x69,
	0xbc, 0xf9, 0xa2, 0x69, 0xa2, 0x4f, 0x08, 0x77, 0x51, 0x74, 0xc9, 0x52, 0x13, 0xde, 0x43, 0x6f,
	0xb2, 0x9e, 0x60, 0x19, 0xec, 0x64, 0x47, 0x30, 0xb1, 0xb1, 0x3a, 0xca, 0xa0, 0xdf, 0x1e, 0xfe,
	0x83, 0xd4, 0xbc, 0xc8, 0x09, 0xdf, 0x00, 0xb7, 0xf5, 0x30, 0x8c, 0xf7, 0xfa, 0x0e, 0xcf, 0xe3,
	0xfd, 0x06, 0x1f, 0x3b, 0x5f, 0x6e, 0x99, 0x65, 0x07, 0xf6, 0xa7, 0x6f, 0xfe, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x22, 0xcf, 0x2c, 0x56, 0xfe, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DockerHostServiceClient is the client API for DockerHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DockerHostServiceClient interface {
	GetContainersCount(ctx context.Context, in *GetContainersCountRequest, opts ...grpc.CallOption) (*GetContainersCountResponse, error)
}

type dockerHostServiceClient struct {
	cc *grpc.ClientConn
}

func NewDockerHostServiceClient(cc *grpc.ClientConn) DockerHostServiceClient {
	return &dockerHostServiceClient{cc}
}

func (c *dockerHostServiceClient) GetContainersCount(ctx context.Context, in *GetContainersCountRequest, opts ...grpc.CallOption) (*GetContainersCountResponse, error) {
	out := new(GetContainersCountResponse)
	err := c.cc.Invoke(ctx, "/DockerHostService/GetContainersCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerHostServiceServer is the server API for DockerHostService service.
type DockerHostServiceServer interface {
	GetContainersCount(context.Context, *GetContainersCountRequest) (*GetContainersCountResponse, error)
}

// UnimplementedDockerHostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDockerHostServiceServer struct {
}

func (*UnimplementedDockerHostServiceServer) GetContainersCount(ctx context.Context, req *GetContainersCountRequest) (*GetContainersCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainersCount not implemented")
}

func RegisterDockerHostServiceServer(s *grpc.Server, srv DockerHostServiceServer) {
	s.RegisterService(&_DockerHostService_serviceDesc, srv)
}

func _DockerHostService_GetContainersCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainersCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerHostServiceServer).GetContainersCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DockerHostService/GetContainersCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerHostServiceServer).GetContainersCount(ctx, req.(*GetContainersCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DockerHostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DockerHostService",
	HandlerType: (*DockerHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContainersCount",
			Handler:    _DockerHostService_GetContainersCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docker-host.proto",
}
